**Data Cleaning**

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("C:/Documents/Bilal/Kuliah/Semester 6/DC/Project UAs/Data/Untitled spreadsheet - Streamlit Dashboard Team & Dataset(hospital_timeseries_2025).csv")

In [6]:
df.head()

,Datetime,Branch,Gender,Age,NPS,CSI,Loyalty,CES,Registration,Doctor Consultation,Nurse Service,Pharmacy Service,Laboratory,Emergency Response,Billing Process,Facility Cleanliness,Staff Friendliness,Waiting Time,Improvement_Feedback
0,07/01/2025 18.47,Always Healthy Hospital Semarang,Male,24,8,4,4,4,3,3,4,4,4,4,5,3,3,3,service good
1,17/01/2025 17.25,Always Healthy Hospital Padang,Female,47,7,4,4,4,3,3,3,5,4,5,4,4,3,3,service good
2,31/01/2025 08.37,Always Healthy Hospital Jakarta,Male,56,8,4,3,4,4,4,3,4,4,5,4,4,5,4,service good
3,28/01/2025 10.45,Always Healthy Hospital Bogor,Female,45,1,4,4,4,4,4,4,4,4,3,4,4,4,3,service good
4,02/01/2025 02.29,Always Healthy Hospital Batam,Male,25,8,4,4,4,4,4,4,5,4,4,5,3,3,3,service good

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Datetime              3600 non-null   str
 1   Branch                3600 non-null   str
 2   Gender                3600 non-null   str
 3   Age                   3600 non-null   int64
 4   NPS                   3600 non-null   int64
 5   CSI                   3600 non-null   int64
 6   Loyalty               3600 non-null   int64
 7   CES                   3600 non-null   int64
 8   Registration          3600 non-null   int64
 9   Doctor Consultation   3600 non-null   int64
 10  Nurse Service         3600 non-null   int64
 11  Pharmacy Service      3600 non-null   int64
 12  Laboratory            3600 non-null   int64
 13  Emergency Response    3600 non-null   int64
 14  Billing Process       3600 non-null   int64
 15  Facility Cleanliness  3600 non-null   int64
 16  Staff Friendliness    3600 non-null   int64
 17  Waiting Time          3600 non-null   int64
 18  Improvement_Feedback  3600 non-null   str
dtypes: int64(15), str(4)
memory usage: 534.5 KB

Tidak ada null dalam dataset

In [12]:
df.duplicated().sum()

np.int64(0)

Tidak ada nilai duplikat dalam dataset

In [20]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

In [23]:
df['datetime'] = pd.to_datetime(
    df['datetime'],
    format="%d/%m/%Y %H.%M"
)

In [25]:
df.head()

,datetime,branch,gender,age,nps,csi,loyalty,ces,registration,doctor_consultation,nurse_service,pharmacy_service,laboratory,emergency_response,billing_process,facility_cleanliness,staff_friendliness,waiting_time,improvement_feedback
0,2025-01-07 18:47:00,Always Healthy Hospital Semarang,Male,24,8,4,4,4,3,3,4,4,4,4,5,3,3,3,service good
1,2025-01-17 17:25:00,Always Healthy Hospital Padang,Female,47,7,4,4,4,3,3,3,5,4,5,4,4,3,3,service good
2,2025-01-31 08:37:00,Always Healthy Hospital Jakarta,Male,56,8,4,3,4,4,4,3,4,4,5,4,4,5,4,service good
3,2025-01-28 10:45:00,Always Healthy Hospital Bogor,Female,45,1,4,4,4,4,4,4,4,4,3,4,4,4,3,service good
4,2025-01-02 02:29:00,Always Healthy Hospital Batam,Male,25,8,4,4,4,4,4,4,5,4,4,5,3,3,3,service good

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              3600 non-null   datetime64[us]
 1   branch                3600 non-null   str
 2   gender                3600 non-null   str
 3   age                   3600 non-null   int64
 4   nps                   3600 non-null   int64
 5   csi                   3600 non-null   int64
 6   loyalty               3600 non-null   int64
 7   ces                   3600 non-null   int64
 8   registration          3600 non-null   int64
 9   doctor_consultation   3600 non-null   int64
 10  nurse_service         3600 non-null   int64
 11  pharmacy_service      3600 non-null   int64
 12  laboratory            3600 non-null   int64
 13  emergency_response    3600 non-null   int64
 14  billing_process       3600 non-null   int64
 15  facility_cleanliness  3600 non-null   int64
 16  staff_friendliness    3600 non-null   int64
 17  waiting_time          3600 non-null   int64
 18  improvement_feedback  3600 non-null   str
dtypes: datetime64[us](1), int64(15), str(3)
memory usage: 534.5 KB